Fix _free_full_params()
I've been getting `AttributeError: 'FlatParameter' object has no attribute '_full_param_padded'` triggered by `p._full_param_padded.record_stream(current_stream)`

Adding a check to not free full params if none have been added.